//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKHNNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtomobils
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avtomobils()
        {
            this.AutoScans = new HashSet<AutoScans>();
            this.Ezdkas = new HashSet<Ezdkas>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> MarkaId { get; set; }
        public string Number { get; set; }
        public int Date { get; set; }
        public Nullable<int> Garage { get; set; }
        public bool Glonass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoScans> AutoScans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ezdkas> Ezdkas { get; set; }
        public virtual MarkaAvtomobils MarkaAvtomobils { get; set; }
        public virtual TypeAvtoes TypeAvtoes { get; set; }
    }
}
