//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKHNNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ezdkas
    {
        public int Id { get; set; }
        public Nullable<int> ArhNumb { get; set; }
        public Nullable<int> AvtoId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Probeg { get; set; }
        public Nullable<int> Ezdki { get; set; }
        public Nullable<int> Time { get; set; }
        public string Voditel { get; set; }
        public bool Pricep { get; set; }
    
        public virtual Avtomobils Avtomobils { get; set; }
    }
}
