//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKHNNC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkaAvtomobils
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarkaAvtomobils()
        {
            this.Avtomobils = new HashSet<Avtomobils>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> SNorm { get; set; }
        public Nullable<decimal> WNorm { get; set; }
        public string Toplivo { get; set; }
        public bool KmMoto { get; set; }
        public decimal NormaEzdka { get; set; }
        public bool EzdkaPricep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avtomobils> Avtomobils { get; set; }
    }
}
